name: Terraform Deployment

on:
  push:
    branches:
      - main  # Runs on every push to main branch
  pull_request:
    branches:
      - main  # Runs on pull request to main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0  # Change to the latest version if needed

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan

#      - name: Terraform Apply
#        if: github.ref == 'refs/heads/main'  # Only applies changes on main branch
#        run: terraform apply -auto-approve